lint-frontend:
  stage: lint
  name: Lint frontend
  runs-on: ubuntu-latest
  timeout-minutes: 10
  rules:
    - changes:
      - apps/web/**/*
      - 'package.json'
      - 'package-lock.json'
      - '.gitlab-ci.yml'
  script:
    - echo "testing lint-frontend"