image: node:20

stages:
  - lint
  - build
  - test

.default_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "main"
      when: manual
      allow_failure: true

lint-frontend:
  stage: lint
  timeout: 10 minutes
  rules:
    - !reference [.default_rules, rules]
    - changes:
      - apps/web/**/*
      - 'package.json'
      - 'package-lock.json'
      - '.gitlab-ci.yml'
  script:
    - npm ci
    - cd apps/web
    - npm run lint

lint-backend:
  stage: lint
  timeout: 10 minutes
  rules:
    - !reference [.default_rules, rules]
    - changes:
      - apps/api/**/*
      - 'package.json'
      - 'package-lock.json'
      - '.gitlab-ci.yml'
  script:
    - npm ci
    - npm run db:generate --workspace=packages/
    - cd apps/api
    - npm run lint

# todo: can you create a variable for shared files?
