services:

  db:
    image: postgres:17 #Change version if needed
    container_name: poetryverse-db
    restart: unless-stopped

    environment: #Discuss 
      POSTGRES_USER: ${POSTGRES_USER:-poetryverse}
      POSTGRES_DB: ${POSTGRES_DB:-poetryverse}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg-2}

      #TODO: implement secure password strategy before final review
      #Options: local-only .env.docker (gitignored) or Docker secrets
    

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-poetryverse} -d ${POSTGRES_DB:-poetryverse}"]
      interval: 5s
      timeout: 5s
      retries: 20


  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile

    container_name: poetryverse-api

    depends_on:
      db:
        condition: service_healthy

    environment:
      PORT: 3001
      NODE_ENV: development

      DATABASE_URL: postgresql://${POSTGRES_USER:-poetryverse}:${POSTGRES_PASSWORD:-pg-2}@db:5432/${POSTGRES_DB:-poetryverse}?schema=public

      GEMINI_API_KEY: ${GEMINI_API_KEY:-}

    ports:
      - "3001:3001"


  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile

      args:
        DATABASE_URL: postgresql://${POSTGRES_USER:-poetryverse}:${POSTGRES_PASSWORD:-pg-2}@db:5432/${POSTGRES_DB:-poetryverse}?schema=public
        NEXT_PUBLIC_API_URL: http://localhost:3001

    container_name: poetryverse-web

    depends_on:
      - api

    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      DATABASE_URL: postgresql://${POSTGRES_USER:-poetryverse}:${POSTGRES_PASSWORD:-pg-2}@db:5432/${POSTGRES_DB:-poetryverse}?schema=public

    ports:
      - "3000:3000"


volumes:
  postgres_data: