services:
  db:
    restart: unless-stopped

  api:
    restart: unless-stopped

    env_file:
      - apps/api/.env.production

    command: >
      sh -c "
        npm install &&
        npm run db:generate --workspace=packages/database &&
        npm run db:deploy --workspace=packages/database &&
        npm run build --workspace=apps/api &&
        npm run start --workspace=apps/api
      "

  web:
    restart: unless-stopped
    
    env_file:
      - apps/web/.env.production

    command: >
      sh -c "
        npm run db:generate --workspace=packages/database &&
        npm run build --workspace=apps/web &&
        npm run start --workspace=apps/web
      "