export const tagIds = {
  adventure: 'adventure',
  animals: 'animals',
  autumn: 'autumn',
  camping: 'camping',
  colour: 'colour',
  dark: 'dark',
  death: 'death',
  dreams: 'dreams',
  earth: 'earth',
  forests: 'forests',
  funny: 'funny',
  general: 'general',
  happy: 'happy',
  life: 'life',
  nature: 'nature',
  nostalgic: 'nostalgic',
  ocean: 'ocean',
  parody: 'parody',
  rage: 'rage',
  random: 'random',
  riddle: 'riddle',
  romance: 'romance',
  sad: 'sad',
  satire: 'satire',
  school: 'school',
  sky: 'sky',
  space: 'space',
  spring: 'spring',
  summer: 'summer',
  technology: 'technology',
  winter: 'winter',
  work: 'work',
}

export const tagData = [
  { id: tagIds.adventure, name: 'Adventure' },
  { id: tagIds.animals, name: 'Animals' },
  { id: tagIds.autumn, name: 'Autumn' },
  { id: tagIds.camping, name: 'Camping' },
  { id: tagIds.colour, name: 'Colour' },
  { id: tagIds.dark, name: 'Dark' },
  { id: tagIds.death, name: 'Death' },
  { id: tagIds.dreams, name: 'Dreams' },
  { id: tagIds.earth, name: 'Earth' },
  { id: tagIds.forests, name: 'Forests' },
  { id: tagIds.funny, name: 'Funny' },
  { id: tagIds.general, name: 'General' },
  { id: tagIds.happy, name: 'Happy' },
  { id: tagIds.life, name: 'Life' },
  { id: tagIds.nature, name: 'Nature' },
  { id: tagIds.nostalgic, name: 'Nostalgic' },
  { id: tagIds.ocean, name: 'Ocean' },
  { id: tagIds.parody, name: 'Parody' },
  { id: tagIds.rage, name: 'Rage' },
  { id: tagIds.random, name: 'Random' },
  { id: tagIds.riddle, name: 'Riddle' },
  { id: tagIds.romance, name: 'Romance' },
  { id: tagIds.sad, name: 'Sad' },
  { id: tagIds.satire, name: 'Satire' },
  { id: tagIds.school, name: 'School' },
  { id: tagIds.sky, name: 'Sky' },
  { id: tagIds.space, name: 'Space' },
  { id: tagIds.spring, name: 'Spring' },
  { id: tagIds.summer, name: 'Summer' },
  { id: tagIds.technology, name: 'Technology' },
  { id: tagIds.winter, name: 'Winter' },
  { id: tagIds.work, name: 'Work' },
]
